project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: "Research Question"
      - href: about_the_data.qmd
        text: "About the Data"
      - href: domestic_violence.qmd
        text: "Domestic Violence"
      - href: substance_abuse.qmd
        text: "Substance Abuse"
    right:
      - href: about.qmd
        text: "About Us"

format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
    highlight: "tomorrow-night"


output:
  self_contained: true

editor: "visual"
